sudo: no
dist: trusty
language: python
python:
  - "3.6"
env:
  matrix:
    - TOXENV=py36-tests
    - TOXENV=py36-flake8
install:
  - pip install coveralls tox
script:
  - tox
after_success: coveralls
